// Define Network settings
export const prodParasPaseo = [
  {
    info: 'paseoAssetHub',
    paraId: 1000,
    providers: {},
    teleport: [-1],
    text: 'Paseo Asset Hub',
  },
  {
    info: 'paseoCollectives',
    paraId: 1001,
    providers: {},
    teleport: [-1],
    text: 'Collectives',
  },
  {
    info: 'paseoBridgeHub',
    paraId: 1002,
    providers: {},
    text: 'Paseo Bridge Hub',
  },
  {
    info: 'paseoPeople',
    paraId: 1004,
    providers: {},
    text: 'Paseo People'
  },
  {
    info: 'paseoCoretime',
    paraId: 1005,
    providers: {},
    text: 'Paseo Coretime'
  },
  {
    homepage: 'https://www.nodle.com/',
    info: 'NodleParadis',
    paraId: 2026,
    providers: {},
    text: 'Nodle',
  },
  {
    homepage: 'https://bifrost.finance',
    info: 'Bifrost(Paseo)',
    paraId: 2030,
    providers: {},
    text: 'Bifrost',
  },
  {
    homepage: 'https://hydration.net/',
    info: 'Hydration(Paseo)',
    paraId: 2034,
    providers: {},
    text: 'Hydration (Paseo)',
  },
  {
    homepage: 'https://integritee.network',
    info: 'integritee',
    paraId: 2039,
    providers: {},
    text: 'Integritee Network (Paseo)',
  },
  {
    homepage: 'https://ajuna.io/',
    info: 'Ajuna(paseo)',
    paraId: 2051,
    providers: {},
    text: 'Ajuna Network (Paseo)',
  },
  {
    homepage: 'https://www.aventus.io/',
    info: 'Aventus',
    paraId: 2056,
    providers: {},
    text: 'Aventus',
  },
  {
    info: 'kilt',
    paraId: 2086,
    providers: {},
    text: 'KILT Peregrine',
  },
  {
    homepage: 'https://zeitgeist.pm/',
    info: 'Zeitgeist',
    paraId: 2101,
    providers: {},
    text: 'Zeitgeist Battery St.',
  },
  {
    homepage: 'https://darwinia.network/',
    info: 'Darwinia Koi',
    paraId: 2105,
    providers: {},
    text: 'Darwinia Koi',
  },
  {
    homepage: 'https://ajuna.io/baju/',
    info: 'Bajun(paseo)',
    paraId: 2119,
    providers: {},
    text: 'Bajun Network (Paseo)',
  },
  {
    homepage: 'https://www.pendulumchain.org/amplitude',
    info: 'Amplitude testnet',
    paraId: 2124,
    providers: {},
    text: 'Amplitude testnet',
  },
  {
    homepage: 'https://www.energyweb.org/',
    info: 'pex',
    paraId: 3345,
    providers: {},
    text: 'PEX',
  },
  {
    info: 'muse',
    paraId: 3369,
    providers: {},
    text: 'Muse network',
  },
  {
    homepage: 'https://www.frequency.xyz',
    info: 'Frequency',
    paraId: 4000,
    providers: {},
    text: 'Frequency Paseo',
  },
  {
    homepage: 'https://popnetwork.xyz/',
    info: 'Pop Network',
    paraId: 4001,
    providers: {},
    text: 'Pop Network',
  },
  {
    homepage: 'https://xcavate.io/',
    info: 'Xcavate',
    paraId: 4003,
    providers: {},
    text: 'Xcavate',
  },
  {
    homepage: 'https://www.myriad.social/',
    info: 'Myriad Social Testnet',
    paraId: 4005,
    providers: {},
    text: 'Myriad Social Testnet',
  },
  {
    homepage: 'https://laosnetwork.io/',
    info: 'laos-sigma',
    paraId: 4006,
    providers: {},
    text: 'Laos Sigma',
  },
  {
    homepage: 'https://hyperbridge.network',
    info: 'Hyperbridge',
    paraId: 4009,
    providers: {},
    text: 'Hyperbridge (Gargantua)',
  },
  {
    homepage: 'https://mandalachain.io',
    info: 'Niskala',
    paraId: 4022,
    providers: {},
    text: 'Niskala',
  },
  {
    info: 'Ideal Network',
    paraId: 4502,
    providers: {},
    text: 'Ideal Network',
  },
];