// Define Network settings
export const prodParasPaseo = [
  {
    info: 'paseoAssetHub',
    paraId: 1000,
    providers: {},
    teleport: [-1],
    text: 'Paseo Asset Hub',
  },
  {
    info: 'paseoCollectives',
    paraId: 1001,
    providers: {},
    teleport: [-1],
    text: 'Collectives',
  },
  {
    info: 'paseoBridgeHub',
    paraId: 1002,
    providers: {},
    text: 'Paseo Bridge Hub',
  },
  {
    homepage: 'https://ajuna.io/',
    info: 'Ajuna(paseo)',
    paraId: 2051,
    providers: {},
    text: 'Ajuna Network (Paseo)',
  },
  {
    homepage: 'https://ajuna.io/',
    info: 'Bajun(paseo)',
    paraId: 2119,
    providers: {},
    text: 'Bajun Network (Paseo)',
  },
  {
    homepage: 'https://bifrost.finance',
    info: 'Bifrost(Paseo)',
    paraId: 2030,
    providers: {},
    text: 'Bifrost',
  },
  {
    homepage: 'https://darwinia.network/',
    info: 'Darwinia Koi',
    paraId: 2105,
    providers: {},
    text: 'Darwinia Koi',
  },
  {
    homepage: 'https://www.frequency.xyz',
    info: 'Frequency',
    paraId: 4000,
    providers: {},
    text: 'Frequency Paseo',
  },
  {
    homepage: 'https://hyperbridge.network',
    info: 'Hyperbridge',
    paraId: 4009,
    providers: {},
    text: 'Hyperbridge (Gargantua)',
  },
  {
    homepage: 'https://integritee.network',
    info: 'integritee',
    paraId: 2039,
    providers: {},
    text: 'Integritee Network (Paseo)',
  },
  {
    info: 'kilt',
    paraId: 2086,
    providers: {},
    text: 'KILT Peregrine',
  },
  {
    homepage: 'https://laosnetwork.io/',
    info: 'laos-sigma',
    paraId: 4006,
    providers: {},
    text: 'Laos Sigma',
  },
  {
    info: 'muse',
    paraId: 3369,
    providers: {},
    text: 'Muse network',
  },
  {
    homepage: 'https://mandalachain.io',
    info: 'Niskala',
    paraId: 4022,
    providers: {},
    text: 'Niskala',
  },
  {
    homepage: 'https://www.nodle.com/',
    info: 'NodleParadis',
    paraId: 2026,
    providers: {},
    text: 'Nodle',
  },
  {
    homepage: 'https://popnetwork.xyz/',
    info: 'Pop Network',
    paraId: 4001,
    providers: {},
    text: 'Pop Network',
  }
];